### ISSUE TITLE
为啥事件触发时回调里不返回event对象呢？

### ISSUE THREAD

**Issue by xingmolu** [cssmagic/action#29]
很多时候在事件函数里需要使用event对象的
```javascript
_handle(actionName, this, ev)


return fn.call(context || window, ev)
```

**Comment by cssmagic** [comment]
谢谢建议。其实我也一直在考虑这一点，虽然技术实现并不困难，但因为要改变接口，我就比较谨慎。

我想听一下你的看法：

* 我一时没有想到会有什么需求一定需要在动作函数里拿到事件对象。你现在遇到了吗？
* 如果动作函数里需要用到事件对象，那 trigger 这个动作函数时如何处理？

**Comment by xingmolu** [comment]
嗯，目前我遇到了这个需求，在一个点击一个大的元素需要隐藏这个元素，但是如果点击里面某个子元素则不会隐藏，我通过e.target来判断的。

之前我写插件一半的事件触发都会返回事件对象，很多时候没有这个不行。

trigger时可以不返回，只不过使用时需要判断下
```javascript
if(e){
}
```
还有更好的方式吗？

**Comment by cssmagic** [comment]
> 目前我遇到了这个需求，在一个点击一个大的元素需要隐藏这个元素，但是如果点击里面某个子元素则不会隐藏

听起来这是一个比较复杂的 UI 效果，能具体再说一说（这个需求的逻辑）吗？

**Comment by xingmolu** [comment]
一个类似于花瓣详情的效果，点开列表中的一个，再当前页面弹出详情。
```html
<div class="picture-view-window" data-action="close-detail">
    <div class="view-datil">
     <!--详情内容-->
    </div>
    <a javascript:; class="window-close"><a>
</div>
```

```css
.picture-view-window{
     position: fixed;
     left: 0;
     right: 0;
     top: 0;
     bottom: 0;
     padding: 50px 0 0;
     z-index: 20;
     background: rgba(0,0,0,0.4);
     background: #000 \9;
     filter: alpha(opacity=40);
     overflow: auto;
}

.view-datil{
    position: absolute;
    left: 50%;
    margin: 0 0 0 -495px;
}
```

需要点击`.picture-view-window`和`.window-close`来关闭详情，但是点击`.view-datil`不会关闭。
